apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mineos-data
  labels:
    app: mineos
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs